<%@ Page Language="C#" MasterPageFile="~/Site.Master" AutoEventWireup="true" CodeBehind="Gas.aspx.cs" Inherits="Deal_Capture_Web_Development.Gas" %>

<asp:Content ID="BodyContent" ContentPlaceHolderID="MainContent" runat="server">
    <div class="jumbotron" style="text-align:center">
        <h1>Gas View</h1>
    </div>
    
    <div class="container-fluid">
                <div class="row">
                    <div class="col-sm-12">
                        <asp:GridView ID="grdGasHead" runat="server" AutoGenerateColumns="False" DataSourceID="GasHead" AutoGenerateDeleteButton="True" AutoGenerateEditButton="True">
                            <Columns>
                                <asp:BoundField DataField="Accounting_Code" HeaderText="Accounting_Code" SortExpression="Accounting_Code" />
                                <asp:BoundField DataField="Prospect_Code" HeaderText="Prospect_Code" SortExpression="Prospect_Code" />
                                <asp:BoundField DataField="Prospect_Name" HeaderText="Prospect_Name" SortExpression="Prospect_Name" />
                                <asp:BoundField DataField="Well_Name" HeaderText="Well_Name" SortExpression="Well_Name" />
                                <asp:BoundField DataField="Well_ID" HeaderText="Well_ID" SortExpression="Well_ID" />
                                <asp:BoundField DataField="Booking_Well_ID" HeaderText="Booking_Well_ID" SortExpression="Booking_Well_ID" />
                                <asp:BoundField DataField="Unit_ID" HeaderText="Unit_ID" SortExpression="Unit_ID" />
                                <asp:BoundField DataField="Tract_ID" HeaderText="Tract_ID" SortExpression="Tract_ID" />
                                <asp:BoundField DataField="Attribute_Volumes" HeaderText="Attribute_Volumes" SortExpression="Attribute_Volumes" />
                                <asp:BoundField DataField="Gas_Processor" HeaderText="Gas_Processor" SortExpression="Gas_Processor" />
                                <asp:BoundField DataField="Purchaser" HeaderText="Purchaser" SortExpression="Purchaser" />
                                <asp:BoundField DataField="Scout_K_Num" HeaderText="Scout_K_Num" SortExpression="Scout_K_Num" />
                                <asp:BoundField DataField="Outside_Contract_Num" HeaderText="Outside_Contract_Num" SortExpression="Outside_Contract_Num" />
                                <asp:BoundField DataField="Meter_Numbers" HeaderText="Meter_Numbers" SortExpression="Meter_Numbers" />
                                <asp:BoundField DataField="Attribute_Volumes1" HeaderText="Attribute_Volumes1" SortExpression="Attribute_Volumes1" />
                                <asp:BoundField DataField="Residue_MMBTU" HeaderText="Residue_MMBTU" SortExpression="Residue_MMBTU" />
                                <asp:BoundField DataField="Net_Residue_MMBTU_X_Contract_Percent" HeaderText="Net_Residue_MMBTU_X_Contract_Percent" SortExpression="Net_Residue_MMBTU_X_Contract_Percent" />
                                <asp:BoundField DataField="Gas_Marketing_Costs" HeaderText="Gas_Marketing_Costs" SortExpression="Gas_Marketing_Costs" />
                                <asp:BoundField DataField="Amount_DIV_day" HeaderText="Amount_DIV_day" SortExpression="Amount_DIV_day" />
                                <asp:BoundField DataField="Fixed_Price_Option" HeaderText="Fixed_Price_Option" SortExpression="Fixed_Price_Option" />
                                <asp:BoundField DataField="Base_Price" HeaderText="Base_Price" SortExpression="Base_Price" />
                                <asp:BoundField DataField="Price1" HeaderText="Price1" SortExpression="Price1" />
                                <asp:BoundField DataField="Percent_1" HeaderText="Percent_1" SortExpression="Percent_1" />
                                <asp:BoundField DataField="Price2" HeaderText="Price2" SortExpression="Price2" />
                                <asp:BoundField DataField="Percent_2" HeaderText="Percent_2" SortExpression="Percent_2" />
                                <asp:BoundField DataField="Price_3" HeaderText="Price_3" SortExpression="Price_3" />
                                <asp:BoundField DataField="Percent_3" HeaderText="Percent_3" SortExpression="Percent_3" />
                                <asp:BoundField DataField="Price_4" HeaderText="Price_4" SortExpression="Price_4" />
                                <asp:BoundField DataField="Percent_4" HeaderText="Percent_4" SortExpression="Percent_4" />
                                <asp:BoundField DataField="Total_Price" HeaderText="Total_Price" SortExpression="Total_Price" />
                                <asp:BoundField DataField="Fund" HeaderText="Fund" SortExpression="Fund" />
                                <asp:BoundField DataField="County" HeaderText="County" SortExpression="County" />
                                <asp:BoundField DataField="Contract" HeaderText="Contract" SortExpression="Contract" />
                                <asp:BoundField DataField="Marketing_Deduct" HeaderText="Marketing_Deduct" SortExpression="Marketing_Deduct" />
                                <asp:BoundField DataField="Longitude" HeaderText="Longitude" SortExpression="Longitude" />
                                <asp:BoundField DataField="Latitude" HeaderText="Latitude" SortExpression="Latitude" />
                                <asp:BoundField DataField="NGL_Purchaser" HeaderText="NGL_Purchaser" SortExpression="NGL_Purchaser" />
                                <asp:BoundField DataField="NGL_K_Num" HeaderText="NGL_K_Num" SortExpression="NGL_K_Num" />
                                <asp:BoundField DataField="NGL_Price_Basis" HeaderText="NGL_Price_Basis" SortExpression="NGL_Price_Basis" />
                                <asp:BoundField DataField="TNF" HeaderText="TNF" SortExpression="TNF" />
                            </Columns>

                        </asp:GridView>
                        <asp:SqlDataSource ID="GasHead" runat="server" ConnectionString="<%$ ConnectionStrings:DealCaptureDBConnectionString %>" SelectCommand="SELECT * FROM [GasHeaderTB]"></asp:SqlDataSource>
                    </div>
                </div>
            </div>
</asp:Content>
