<%@ Page Language="C#" MasterPageFile="~/Site.Master" AutoEventWireup="true" CodeBehind="GasSum.aspx.cs" Inherits="Deal_Capture_Web_Development.GasSum" %>

<asp:Content ID="BodyContent" ContentPlaceHolderID="MainContent" runat="server">
    <!-- Title of Page -->
    <div class="jumbotron" style="text-align:center">
        <h1>Gas Summarized</h1>
    </div>
    <!-- Content of the Page -->
    <div class="container-fluid">
        <!-- Search Bar --> 
        <div class="row">
            <div class="col-sm-12" style="justify-content:center">
                <asp:TextBox ID="txtSearch" runat="server" />
                <asp:Button Text="Search" runat="server" />
                <asp:Label Text="Seach by accounting number, prospects code, prospect nambe, well name, well id" runat="server" />
            </div>
        </div>
        <!-- Data Grid -->
        <div class="row">
            <div class="col-sm-12">
                <asp:GridView ID="grdGasSum" runat="server" AllowPaging="True" AllowSorting="True" AutoGenerateColumns="False" AutoGenerateDeleteButton="True" AutoGenerateEditButton="True" DataKeyNames="ID" DataSourceID="GasSumData">
                    <Columns>
                        <asp:BoundField DataField="ID" HeaderText="ID" InsertVisible="False" ReadOnly="True" SortExpression="ID" />
                        <asp:BoundField DataField="MonthNumber" HeaderText="MonthNumber" SortExpression="MonthNumber" />
                        <asp:BoundField DataField="CostCenterCode" HeaderText="CostCenterCode" SortExpression="CostCenterCode" />
                        <asp:BoundField DataField="CostCenterName" HeaderText="CostCenterName" SortExpression="CostCenterName" />
                        <asp:BoundField DataField="SumOfNetVolume" HeaderText="SumOfNetVolume" SortExpression="SumOfNetVolume" />
                        <asp:BoundField DataField="SumOfNetAmount" HeaderText="SumOfNetAmount" SortExpression="SumOfNetAmount" />
                        <asp:BoundField DataField="Mth3raProd" HeaderText="Mth3raProd" SortExpression="Mth3raProd" />
                        <asp:BoundField DataField="Mth6raProd" HeaderText="Mth6raProd" SortExpression="Mth6raProd" />
                        <asp:BoundField DataField="Mth3raRev" HeaderText="Mth3raRev" SortExpression="Mth3raRev" />
                        <asp:BoundField DataField="Mth6raRev" HeaderText="Mth6raRev" SortExpression="Mth6raRev" />
                        <asp:BoundField DataField="Volume1" HeaderText="Volume1" SortExpression="Volume1" />
                        <asp:BoundField DataField="Volume2" HeaderText="Volume2" SortExpression="Volume2" />
                        <asp:BoundField DataField="Volume3" HeaderText="Volume3" SortExpression="Volume3" />
                        <asp:BoundField DataField="Volume4" HeaderText="Volume4" SortExpression="Volume4" />
                        <asp:BoundField DataField="Mth3raProd_Day" HeaderText="Mth3raProd_Day" SortExpression="Mth3raProd_Day" />
                        <asp:BoundField DataField="Mth6raProd_Day" HeaderText="Mth6raProd_Day" SortExpression="Mth6raProd_Day" />
                        <asp:BoundField DataField="Gross6Mth_MMbtu" HeaderText="Gross6Mth_MMbtu" SortExpression="Gross6Mth_MMbtu" />
                        <asp:BoundField DataField="Gross3Mth_MMbtu" HeaderText="Gross3Mth_MMbtu" SortExpression="Gross3Mth_MMbtu" />
                        <asp:BoundField DataField="Mkt6Mth_Mmbtu" HeaderText="Mkt6Mth_Mmbtu" SortExpression="Mkt6Mth_Mmbtu" />
                        <asp:BoundField DataField="Mkt3Mth_Mmbtu" HeaderText="Mkt3Mth_Mmbtu" SortExpression="Mkt3Mth_Mmbtu" />
                        <asp:BoundField DataField="NetPrice6Mth_Mmbtu" HeaderText="NetPrice6Mth_Mmbtu" SortExpression="NetPrice6Mth_Mmbtu" />
                        <asp:BoundField DataField="NetPrice3Mth_Mmbtu" HeaderText="NetPrice3Mth_Mmbtu" SortExpression="NetPrice3Mth_Mmbtu" />
                    </Columns>
                </asp:GridView>
                <asp:SqlDataSource ID="GasSumData" runat="server" ConnectionString="<%$ ConnectionStrings:DealCaptureDBConnectionString %>" 
                    SelectCommand="SELECT * FROM [GasSummarizedTB]"
                    UpdateCommand="UPDATE [GasSummarizedTB] set MonthNumber=@MonthNumber, CostCenterCode=@CostCenterCode, SumOfNetVolume=@SumOfNetVolume, SumOfNetAmount=@SumOfNetAmount, Mth3raProd=@Mth3raProd, Mth6raProd=@Mth6raProd, Mth3raRev=@Mth3raRev, Mth6raRev=@Mth6raRev, Volume1=@Volume1, Volume2=@Volume2, Volume3=@Volume3, Volume4=@Volume4, Mth3raProd_Day=@Mth3raProd_Day, Mth6raProd_Day=@Mth6raProd_Day, Gross6Mth_MMbtu=@Gross6Mth_MMbtu, Gross3Mth_MMbtu=@Gross3Mth_MMbtu, Mkt6Mth_Mmbtu=@Mkt6Mth_Mmbtu, Mkt3Mth_Mmbtu=@Mkt3Mth_Mmbtu, NetPrice6Mth_Mmbtu=@NetPrice6Mth_Mmbtu, NetPrice3Mth_Mmbtu=@NetPrice3Mth_Mmbtu Where ID=@ID">

                </asp:SqlDataSource>
            </div>
        </div>
    </div>
</asp:Content>